import { assertEquals } from "@std/assert";
import { solvePart1, solvePart2 } from "./main.ts";

Deno.test(function part1_example() {
  const exampleInput1 = `............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............`;
  assertEquals(solvePart1(exampleInput1), 14);
});

Deno.test(function part2_example_a() {
  const exampleInput2 = `............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............`;
  assertEquals(solvePart2(exampleInput2), 34);
});

Deno.test(function part2_example_b() {
  const exampleInput2 = `T.........
...T......
.T........
..........
..........
..........
..........
..........
..........
..........`;
  assertEquals(solvePart2(exampleInput2), 9);
});
